import * as mongoose from 'mongoose';
const Schema = mongoose.Schema;

export const EmployeeSettingSchema = new Schema(
    {
        number: { type: String },
        idNumber: { type: String },
        employmentType: { type: String },
        remarks: { type: String },
        gender: { type: String },
        department: { type: String },
        user: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
        workingYears: { type: String },
        nickName: { type: String },
        firstName: { type: String },
        lastName: { type: String },
        address: { type: String },
        phoneNum: { type: String },
        email: { type: String },
        emergencyPerson: { type: String },
        emergencyTel: { type: String },
        hireDate: { type: Date },
        issueDate: { type: Date },
        position: { type: String },
        passPortNo: { type: String },
        passType: { type: String },
        scpr: { type: String },
        annualLeave: { type: Number },
        remainingAnnualLeave: { type: Number },
        sickLeave: { type: Number },
        remainingSickLeave: { type: Number },
        childcareLeave: { type: Number },
        remainingChildCareLeave: { type: Number },
        inLieuLeave: { type: Number },
        remainingInLieuLeave: { type: Number },
        // maternityLeave: { type: Number },
        // remainingMaternityLeave: { type: Number },
        // paternityLeave: { type: Number },
        //remainingPaternityLeave: { type: Number },
        // sharedPaternityLeave: { type: Number },
        // remainingSharedPaternityLeave: { type: Number },
        leaveCarriedForward: { type: Number },
        // remainingUnpaidLeave: { type: Number },
        reservistLeave: { type: Number },
        remainingReservistLeave: { type: Number },
        cpfFEmployer: { type: String },
        cpfFEmployee: { type: String },
        levy: { type: String },
        sdl: { type: String },
        allowance: { type: String },
        basicSalary: { type: String },
        // status: { type: String, default: 'draft' },

    },
    {
        timestamps: { createdAt: 'createdAt', updatedAt: 'updatedAt' },
    },
);
EmployeeSettingSchema.set('toJSON', { virtuals: true });